// Capacitor needs a webDir. The app is one file, so "building" is a copy —
// this keeps index.html at the repo root as the standalone web app and gives
// the native shell the same bytes, rather than forking the codebase.
import { mkdir, copyFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const www = resolve(root, "www");

await mkdir(www, { recursive: true });
await copyFile(resolve(root, "index.html"), resolve(www, "index.html"));
await writeFile(
  resolve(www, ".gitignore"),
  "# Generated by scripts/build-www.mjs — edit index.html at the repo root instead.\n*\n"
);
console.log("www/index.html written");
